version: '3.8'
services:
  paymentgateway:
    build: PaymentGateway/
    ports:
      - 9000:80
    environment:
      MySqlConfig__ConnectionString: Server=mysql;Uid=rw_user;Pwd=Warrington4
      ElasticConfiguration__Uri: http://es01:9200
    depends_on:
      - mysql
      - es01
      - kib01
    networks:
      - pg_network
  mysql:
    image: mysql:5.7
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
#      - D:\JunSalonSQL:/var/lib/mysql
      - ./InitialiseDB/:/docker-entrypoint-initdb.d
    networks:
      - pg_network
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - pg_network
  kib01:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - pg_network

volumes:
  data01:
    driver: local

networks:
  pg_network:
    driver: bridge